<a href="https://colab.research.google.com/github/melanieyes/linear-regression/blob/main/multiva_nonlinear_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

#1.Load Data

In [2]:
df = pd.read_csv('./Fish.csv')
df

Species  Weight  VerticalLen  DiagonalLen  CrossLen   Height   Width
0     Bream   242.0         23.2         25.4      30.0  11.5200  4.0200
1     Bream   290.0         24.0         26.3      31.2  12.4800  4.3056
2     Bream   340.0         23.9         26.5      31.1  12.3778  4.6961
3     Bream   363.0         26.3         29.0      33.5  12.7300  4.4555
4     Bream   430.0         26.5         29.0      34.0  12.4440  5.1340
..      ...     ...          ...          ...       ...      ...     ...
154   Smelt    12.2         11.5         12.2      13.4   2.0904  1.3936
155   Smelt    13.4         11.7         12.4      13.5   2.4300  1.2690
156   Smelt    12.2         12.1         13.0      13.8   2.2770  1.2558
157   Smelt    19.7         13.2         14.3      15.2   2.8728  2.0672
158   Smelt    19.9         13.8         15.0      16.2   2.9322  1.8792

[159 rows x 7 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Species      159 non-null    object 
 1   Weight       159 non-null    float64
 2   VerticalLen  159 non-null    float64
 3   DiagonalLen  159 non-null    float64
 4   CrossLen     159 non-null    float64
 5   Height       159 non-null    float64
 6   Width        159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


**One hot encoding**

In [4]:
df

Species  Weight  VerticalLen  DiagonalLen  CrossLen   Height   Width
0     Bream   242.0         23.2         25.4      30.0  11.5200  4.0200
1     Bream   290.0         24.0         26.3      31.2  12.4800  4.3056
2     Bream   340.0         23.9         26.5      31.1  12.3778  4.6961
3     Bream   363.0         26.3         29.0      33.5  12.7300  4.4555
4     Bream   430.0         26.5         29.0      34.0  12.4440  5.1340
..      ...     ...          ...          ...       ...      ...     ...
154   Smelt    12.2         11.5         12.2      13.4   2.0904  1.3936
155   Smelt    13.4         11.7         12.4      13.5   2.4300  1.2690
156   Smelt    12.2         12.1         13.0      13.8   2.2770  1.2558
157   Smelt    19.7         13.2         14.3      15.2   2.8728  2.0672
158   Smelt    19.9         13.8         15.0      16.2   2.9322  1.8792

[159 rows x 7 columns]

In [5]:
encode_species = pd.get_dummies(df.Species)
encode_species.head(5)

Bream  Parkki  Perch   Pike  Roach  Smelt  Whitefish
0   True   False  False  False  False  False      False
1   True   False  False  False  False  False      False
2   True   False  False  False  False  False      False
3   True   False  False  False  False  False      False
4   True   False  False  False  False  False      False

**Label Encoding**

In [6]:
df["Species"] = df["Species"].astype('category')
label_ecnoding_species = df["Species"].cat.codes
label_ecnoding_species

0      0
1      0
2      0
3      0
4      0
      ..
154    5
155    5
156    5
157    5
158    5
Length: 159, dtype: int8

In [7]:
new_df = pd.concat([df, encode_species], axis='columns')
new_df

Species  Weight  VerticalLen  DiagonalLen  CrossLen   Height   Width  \
0     Bream   242.0         23.2         25.4      30.0  11.5200  4.0200   
1     Bream   290.0         24.0         26.3      31.2  12.4800  4.3056   
2     Bream   340.0         23.9         26.5      31.1  12.3778  4.6961   
3     Bream   363.0         26.3         29.0      33.5  12.7300  4.4555   
4     Bream   430.0         26.5         29.0      34.0  12.4440  5.1340   
..      ...     ...          ...          ...       ...      ...     ...   
154   Smelt    12.2         11.5         12.2      13.4   2.0904  1.3936   
155   Smelt    13.4         11.7         12.4      13.5   2.4300  1.2690   
156   Smelt    12.2         12.1         13.0      13.8   2.2770  1.2558   
157   Smelt    19.7         13.2         14.3      15.2   2.8728  2.0672   
158   Smelt    19.9         13.8         15.0      16.2   2.9322  1.8792   

     Bream  Parkki  Perch   Pike  Roach  Smelt  Whitefish  
0     True   False  False  False  False  False      False  
1     True   False  False  False  False  False      False  
2     True   False  False  False  False  False      False  
3     True   False  False  False  False  False      False  
4     True   False  False  False  False  False      False  
..     ...     ...    ...    ...    ...    ...        ...  
154  False   False  False  False  False   True      False  
155  False   False  False  False  False   True      False  
156  False   False  False  False  False   True      False  
157  False   False  False  False  False   True      False  
158  False   False  False  False  False   True      False  

[159 rows x 14 columns]

In [8]:
X = new_df[[
    'VerticalLen', 'DiagonalLen', 'CrossLen', 'Height', 'Width',
    'Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'
]]
y = new_df['Weight']

In [9]:
X = X.values
y = y.values

In [10]:
X

array([[23.2, 25.4, 30.0, ..., False, False, False],
       [24.0, 26.3, 31.2, ..., False, False, False],
       [23.9, 26.5, 31.1, ..., False, False, False],
       ...,
       [12.1, 13.0, 13.8, ..., False, True, False],
       [13.2, 14.3, 15.2, ..., False, True, False],
       [13.8, 15.0, 16.2, ..., False, True, False]], dtype=object)

In [11]:
X_data = np.hstack((np.ones((X.shape[0], 1)), X))
X_data

array([[1.0, 23.2, 25.4, ..., False, False, False],
       [1.0, 24.0, 26.3, ..., False, False, False],
       [1.0, 23.9, 26.5, ..., False, False, False],
       ...,
       [1.0, 12.1, 13.0, ..., False, True, False],
       [1.0, 13.2, 14.3, ..., False, True, False],
       [1.0, 13.8, 15.0, ..., False, True, False]], dtype=object)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 13)
X_test shape:  (32, 13)
y_train shape:  (127,)
y_train shape:  (32,)


#Linear Regression

In [14]:
def r2score(y_pred, y):
    rss = np.sum((y_pred - y) ** 2)
    tss = np.sum((y-y.mean()) ** 2)

    r2 = 1 - (rss / tss)
    return r2

In [15]:
class LinearRegression:
    def __init__(self, X_data, y_target, learning_rate=0.00001, num_epochs=10000):
        self.X_data = X_data
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
        self.num_samples = self.X_data.shape[0]

        # Initial Coefficients
        self.theta = np.random.randn(self.X_data.shape[1])
        self.losses = []

    def compute_loss(self, y_pred, y_target):
        loss = (y_pred-y_target)*(y_pred-y_target)
        loss = np.mean(loss)
        return loss

    def predict(self, X_data):
        y_pred = X_data.dot(self.theta)
        return y_pred

    def fit(self):
        for epoch in range(self.num_epochs):
            # predict
            y_pred = self.predict(self.X_data)

            # compute loss
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            # compute gradient
            k = 2*(y_pred-self.y_target)
            gradients = self.X_data.T.dot(k)/self.num_samples

            # update weight
            self.theta = self.theta - self.learning_rate*gradients

            print(f'Epoch: {epoch} - Loss: {loss}')

        return {
            'loss': sum(self.losses)/len(self.losses),
            'weight': self.theta
        }

In [16]:
linear_model = LinearRegression(X_train, y_train, learning_rate=0.00001, num_epochs=1000)
linear_model.fit()

Epoch: 0 - Loss: 252401.19661184997
Epoch: 1 - Loss: 229110.62479879614
Epoch: 2 - Loss: 208453.66344804157
Epoch: 3 - Loss: 190132.5106223198
Epoch: 4 - Loss: 173883.03906601833
Epoch: 5 - Loss: 159470.98835827544
Epoch: 6 - Loss: 146688.5876476697
Epoch: 7 - Loss: 135351.56027943586
Epoch: 8 - Loss: 125296.46713177525
Epoch: 9 - Loss: 116378.35036090546
Epoch: 10 - Loss: 108468.64358539484
Epoch: 11 - Loss: 101453.31838150867
Epoch: 12 - Loss: 95231.24036812346
Epoch: 13 - Loss: 89712.71118135528
Epoch: 14 - Loss: 84818.1753189698
Epoch: 15 - Loss: 80477.07321152011
Epoch: 16 - Loss: 76626.82398526727
Epoch: 17 - Loss: 73211.92325166968
Epoch: 18 - Loss: 70183.14291653002
Epoch: 19 - Loss: 67496.82147267737
Epoch: 20 - Loss: 65114.234544539446
Epoch: 21 - Loss: 63001.036609923925
Epoch: 22 - Loss: 61126.76585047448
Epoch: 23 - Loss: 59464.404992370386
Epoch: 24 - Loss: 57989.99180603752
Epoch: 25 - Loss: 56682.27364955606
Epoch: 26 - Loss: 55522.40107541624
Epoch: 27 - Loss: 54493.65

{'loss': 48132.109058611204,
 'weight': array([-2.6963385743989456, 4.735942528364547, 4.696312613682611,
        5.481674587453082, 2.1092312302805487, 0.3820096657886089,
        -0.06327784370774324, 0.9399071839293803, 0.16780616479464253,
        -0.9898356593478945, -1.0931283610697926, -1.2505280029751813,
        0.5718361926768732], dtype=object)}

In [17]:
preds = linear_model.predict(X_train)
r2score(preds, y_train)

0.6242675445476604

In [18]:
preds = linear_model.predict(X_test)
r2score(preds, y_test)

0.6469239600326044

#Polynomial Regression

##Simple Approach
**Form**
$(a+b)^2 => a^2 + b^2 + a + b + 1$

In [19]:
def create_polynomial_features(X, degree=2):
    """Creates the polynomial features
    Args:
        X: A array for the data.
        degree: A intege for the degree of
        the generated polynomial function.
    """
    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

In [20]:
X_new = np.array([[1, 2], [3, 4]])
X_new

array([[1, 2],
       [3, 4]])

In [21]:
create_polynomial_features(X_new, degree=2)

array([[ 1,  1,  2,  4],
       [ 3,  9,  4, 16]])

In [22]:
create_polynomial_features(X_new, degree=3)

array([[ 1,  1,  1,  2,  4,  8],
       [ 3,  9, 27,  4, 16, 64]])

In [23]:
X_poly = create_polynomial_features(X, degree=2)
X_poly

array([[23.2, 538.24, 25.4, ..., 0, False, 0],
       [24.0, 576.0, 26.3, ..., 0, False, 0],
       [23.9, 571.2099999999999, 26.5, ..., 0, False, 0],
       ...,
       [12.1, 146.41, 13.0, ..., 1, False, 0],
       [13.2, 174.23999999999998, 14.3, ..., 1, False, 0],
       [13.8, 190.44000000000003, 15.0, ..., 1, False, 0]], dtype=object)

In [24]:
X_poly.shape

(159, 24)

In [25]:
X_data = np.hstack((np.ones((X_poly.shape[0], 1)), X_poly))
X_data

array([[1.0, 23.2, 538.24, ..., 0, False, 0],
       [1.0, 24.0, 576.0, ..., 0, False, 0],
       [1.0, 23.9, 571.2099999999999, ..., 0, False, 0],
       ...,
       [1.0, 12.1, 146.41, ..., 1, False, 0],
       [1.0, 13.2, 174.23999999999998, ..., 1, False, 0],
       [1.0, 13.8, 190.44000000000003, ..., 1, False, 0]], dtype=object)

In [26]:
X_data.shape, y.shape

((159, 25), (159,))

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 25)
X_test shape:  (32, 25)
y_train shape:  (127,)
y_train shape:  (32,)


In [28]:
poly_model = LinearRegression(X_train, y_train, learning_rate=0.0000001, num_epochs=100000)
poly_model.fit()

Streaming output truncated to the last 5000 lines.
Epoch: 95000 - Loss: 3653.5159886613324
Epoch: 95001 - Loss: 3653.5094884016557
Epoch: 95002 - Loss: 3653.5029882342824
Epoch: 95003 - Loss: 3653.496488159201
Epoch: 95004 - Loss: 3653.489988176411
Epoch: 95005 - Loss: 3653.4834882859122
Epoch: 95006 - Loss: 3653.4769884877014
Epoch: 95007 - Loss: 3653.4704887817834
Epoch: 95008 - Loss: 3653.463989168144
Epoch: 95009 - Loss: 3653.4574896467925
Epoch: 95010 - Loss: 3653.450990217727
Epoch: 95011 - Loss: 3653.4444908809323
Epoch: 95012 - Loss: 3653.437991636422
Epoch: 95013 - Loss: 3653.4314924841833
Epoch: 95014 - Loss: 3653.424993424221
Epoch: 95015 - Loss: 3653.4184944565327
Epoch: 95016 - Loss: 3653.411995581114
Epoch: 95017 - Loss: 3653.405496797968
Epoch: 95018 - Loss: 3653.3989981070854
Epoch: 95019 - Loss: 3653.3924995084662
Epoch: 95020 - Loss: 3653.386001002109
Epoch: 95021 - Loss: 3653.379502588022
Epoch: 95022 - Loss: 3653.3730042661846
Epoch: 95023 - Loss: 3653.3665060366006

{'loss': 5036.652196756063,
 'weight': array([-0.4916531102505274, -2.67033319366431, -0.01800930740042982,
        -2.670543324135543, 1.0768677192873577, -3.4525790005006023,
        -0.5457440710700093, -0.7167862563991497, 1.7981500140689,
        -1.2079918224027495, 4.850512655763795, -1.1332153898300323,
        0.7119855688097698, 0.9041550526411195, -0.25047602976157946,
        0.4380570233812717, -1.0457327009144273, 0.887766624708687,
        -0.7342137214652961, 1.5397014908330509, 0.2807176147048838,
        0.09525321334080604, -1.2349531256695, 0.05716963268998151,
        1.086791889823638], dtype=object)}

In [29]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

0.970534585800315

In [30]:
preds = poly_model.predict(X_test)
r2score(preds, y_test)

0.9726315272224189

## **Sklearn**

In [31]:
X.shape

(159, 12)

In [32]:
y.shape

(159,)

In [33]:
from sklearn.preprocessing import PolynomialFeatures

In [34]:
poly_features = PolynomialFeatures(degree=2)

In [35]:
X_data = poly_features.fit_transform(X)
X_data

array([[ 1. , 23.2, 25.4, ...,  0. ,  0. ,  0. ],
       [ 1. , 24. , 26.3, ...,  0. ,  0. ,  0. ],
       [ 1. , 23.9, 26.5, ...,  0. ,  0. ,  0. ],
       ...,
       [ 1. , 12.1, 13. , ...,  1. ,  0. ,  0. ],
       [ 1. , 13.2, 14.3, ...,  1. ,  0. ,  0. ],
       [ 1. , 13.8, 15. , ...,  1. ,  0. ,  0. ]])

In [36]:
X_data.shape

(159, 91)

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 91)
X_test shape:  (32, 91)
y_train shape:  (127,)
y_train shape:  (32,)


In [38]:
poly_model = LinearRegression(X_train, y_train, learning_rate=0.0000001, num_epochs=100000)
poly_model.fit()

Streaming output truncated to the last 5000 lines.
Epoch: 95000 - Loss: 2658.1781724296825
Epoch: 95001 - Loss: 2658.1694864770934
Epoch: 95002 - Loss: 2658.1608007267264
Epoch: 95003 - Loss: 2658.1521151785846
Epoch: 95004 - Loss: 2658.1434298326544
Epoch: 95005 - Loss: 2658.134744688935
Epoch: 95006 - Loss: 2658.1260597474193
Epoch: 95007 - Loss: 2658.1173750081
Epoch: 95008 - Loss: 2658.108690470972
Epoch: 95009 - Loss: 2658.1000061360387
Epoch: 95010 - Loss: 2658.091322003279
Epoch: 95011 - Loss: 2658.082638072697
Epoch: 95012 - Loss: 2658.0739543442896
Epoch: 95013 - Loss: 2658.065270818042
Epoch: 95014 - Loss: 2658.0565874939616
Epoch: 95015 - Loss: 2658.0479043720247
Epoch: 95016 - Loss: 2658.0392214522417
Epoch: 95017 - Loss: 2658.0305387345984
Epoch: 95018 - Loss: 2658.0218562191035
Epoch: 95019 - Loss: 2658.0131739057306
Epoch: 95020 - Loss: 2658.0044917944892
Epoch: 95021 - Loss: 2657.995809885362
Epoch: 95022 - Loss: 2657.987128178357
Epoch: 95023 - Loss: 2657.97844667346
E

{'loss': 4478.073326276516,
 'weight': array([ 0.39171089, -3.511368  , -3.54745101, -1.77895578, -0.42223778,
        -1.3084727 , -0.75349313, -1.64778307, -1.81560691, -0.80949399,
         0.51291416, -1.1877225 ,  1.04443613,  0.38325944, -0.09135943,
         0.1105465 , -1.41437376,  0.63422212,  0.12117846,  0.49628322,
         1.57992382, -1.86406883, -0.16718638,  0.25199372, -0.04255547,
        -0.06539572,  0.6496902 ,  0.00507403,  1.65643784, -1.25903696,
        -1.68823042, -1.47495794, -1.4857775 ,  0.03728053,  0.78001351,
         1.33167281, -0.49510723,  1.09271424, -0.37895065, -0.67111723,
        -1.6849312 , -0.70847636, -1.63572681, -1.56570699, -0.43180405,
        -0.99872955,  1.05037642,  0.62438756, -1.9455657 ,  0.98098152,
        -1.22897683,  0.11087329, -0.17912243,  0.44549122, -1.23124586,
        -0.90569326, -0.10141458,  1.14364961, -1.18830758,  0.4930205 ,
         0.36927215,  0.09921013,  1.51757581,  0.51956843,  0.37090043,
        -0.70

In [39]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

0.9787098092732485